# Generated by Django 4.2.30 on 2026-06-30 06:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('mid_term', 'Mid-Term Assessment'), ('final', 'Final Assessment')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all criterion scores.', max_digits=5)),
                ('max_possible', models.PositiveSmallIntegerField(default=0, help_text='Sum of all max_scores at time of submission.')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='placements.application')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
                'unique_together': {('application', 'assessment_type')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.PositiveSmallIntegerField(default=10)),
                ('category', models.CharField(choices=[('soft_skills', 'Soft Skills'), ('technical_skills', 'Technical Skills')], default='soft_skills', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order on the assessment form.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assessment Criterion',
                'verbose_name_plural': 'Assessment Criteria',
                'ordering': ['order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_comment', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], default='satisfactory', max_length=20)),
                ('student_acknowledged', models.BooleanField(default=False)),
                ('student_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True, help_text='Optional feedback specific to this criterion.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessment.assessment')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessment.assessmentcriteria')),
            ],
            options={
                'unique_together': {('assessment', 'criterion')},
            },
        ),
    ]
