# Generated by Django 4.2.30 on 2026-06-30 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(blank=True)),
                ('location', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slots_available', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('target_department', models.CharField(choices=[('All Departments', 'All Departments'), ('Computer Science', 'Computer Science'), ('Software and Web Development', 'Software and Web Development'), ('Business Administration', 'Business Administration'), ('Accountancy', 'Accountancy'), ('Electrical/Electronic Engineering', 'Electrical/Electronic Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Statistics', 'Statistics'), ('Mass Communication', 'Mass Communication'), ('Office Technology and Management', 'Office Technology and Management'), ('Marketing', 'Marketing')], default='All Departments', help_text="Which department is this placement for? Choose 'All Departments' to show to everyone.", max_length=100)),
                ('target_programme', models.CharField(choices=[('Both', 'Both (ND & HND)'), ('ND', 'ND'), ('HND', 'HND')], default='Both', help_text='ND, HND, or Both.', max_length=10)),
                ('target_level', models.CharField(choices=[('All Levels', 'All Levels'), ('ND1', 'ND 1'), ('ND2', 'ND 2'), ('HND1', 'HND 1'), ('HND2', 'HND 2')], default='All Levels', help_text='Specific level or All Levels.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(limit_choices_to={'role': 'coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placement')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'placement')},
            },
        ),
    ]
