# Generated by Django 4.2.30 on 2026-07-09 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placements', '0003_backfill_placement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, help_text='The industry supervisor responsible for students in this placement', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
