# Generated by Django 4.2.30 on 2026-07-11 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placements', '0004_placement_assigned_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Optional note shown to the supervisor, e.g. reason for rejection.'),
        ),
        migrations.AddField(
            model_name='placement',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='placement',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placement',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Whoever originally submitted this listing — coordinator or supervisor.', limit_choices_to={'role__in': ['coordinator', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placement',
            name='posted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placement',
            name='target_department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software and Web Development', 'Software and Web Development'), ('Business Administration', 'Business Administration'), ('Accountancy', 'Accountancy'), ('Electrical/Electronic Engineering', 'Electrical/Electronic Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Statistics', 'Statistics'), ('Mass Communication', 'Mass Communication'), ('Office Technology and Management', 'Office Technology and Management'), ('Marketing', 'Marketing')], default='', help_text="Which single department is this placement for. Only students in this exact department will see it — there is no 'show to everyone' option.", max_length=100),
        ),
    ]
