# Generated by Django 4.2.30 on 2026-08-09 13:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_placement_approval_notes_placement_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cvs/'),
        ),
    ]
