# Generated by Django 4.2.30 on 2026-06-30 06:27

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Industry Supervisor'), ('coordinator', 'School Coordinator')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('matric_number', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, choices=[('All Departments', 'All Departments'), ('Computer Science', 'Computer Science'), ('Software and Web Development', 'Software and Web Development'), ('Business Administration', 'Business Administration'), ('Accountancy', 'Accountancy'), ('Electrical/Electronic Engineering', 'Electrical/Electronic Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Statistics', 'Statistics'), ('Mass Communication', 'Mass Communication'), ('Office Technology and Management', 'Office Technology and Management'), ('Marketing', 'Marketing')], default='', max_length=100)),
                ('programme', models.CharField(blank=True, choices=[('ND', 'ND'), ('HND', 'HND')], default='', max_length=10)),
                ('level', models.CharField(blank=True, choices=[('All Levels', 'All Levels'), ('ND1', 'ND 1'), ('ND2', 'ND 2'), ('HND1', 'HND 1'), ('HND2', 'HND 2')], default='', max_length=20)),
                ('academic_session', models.CharField(blank=True, default='2024/2025', help_text='e.g. 2024/2025', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('company_address', models.TextField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=20)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
