# Generated by Django 4.2.30 on 2026-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Software and Web Development', 'Software and Web Development'), ('Business Administration', 'Business Administration'), ('Accountancy', 'Accountancy'), ('Electrical/Electronic Engineering', 'Electrical/Electronic Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Statistics', 'Statistics'), ('Mass Communication', 'Mass Communication'), ('Office Technology and Management', 'Office Technology and Management'), ('Marketing', 'Marketing')], default='', help_text="Coordinator's department. Must match student department exactly for filtering to work — hence this is a dropdown, not free text.", max_length=100),
        ),
    ]
