# Generated by Django 4.2.30 on 2026-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('supervisor', 'Industry Supervisor'), ('coordinator', 'School Coordinator')], default='', max_length=20),
        ),
    ]
