# Generated by Django 4.2.30 on 2026-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supervisor_department',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Software and Web Development', 'Software and Web Development'), ('Business Administration', 'Business Administration'), ('Accountancy', 'Accountancy'), ('Electrical/Electronic Engineering', 'Electrical/Electronic Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Statistics', 'Statistics'), ('Mass Communication', 'Mass Communication'), ('Office Technology and Management', 'Office Technology and Management'), ('Marketing', 'Marketing')], default='', help_text='The one department this supervisor posts placements for. Every placement they submit automatically targets this department — it cannot be changed per-posting.', max_length=100),
        ),
    ]
