# Generated by Django 4.2.30 on 2026-06-30 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'Everyone'), ('students', 'All Students'), ('supervisors', 'All Supervisors'), ('specific_student', 'Specific Student'), ('specific_supervisor', 'Specific Supervisor')], default='all', max_length=25)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(limit_choices_to={'role': 'coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('specific_user', models.ForeignKey(blank=True, help_text='Required when audience is a specific student/supervisor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.Case(models.When(priority='urgent', then=0), models.When(priority='important', then=1), default=2, output_field=models.IntegerField()), '-created_at'],
            },
        ),
    ]
