# Generated by Django 4.2.30 on 2026-07-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_department',
            field=models.CharField(blank=True, default='', help_text='Used when targeting a specific department.', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='specific_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students Only (My Department)'), ('supervisors', 'All Supervisors'), ('specific_department', 'Specific Department'), ('specific_student', 'Specific Student'), ('specific_supervisor', 'Specific Supervisor')], default='all', max_length=25),
        ),
    ]
