# Generated by Django 4.2.30 on 2026-06-30 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary', models.TextField()),
                ('challenges_faced', models.TextField(blank=True)),
                ('next_week_plan', models.TextField(blank=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='placements.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'ordering': ['-week_start'],
                'unique_together': {('application', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_description', models.TextField()),
                ('skills_gained', models.CharField(blank=True, max_length=300)),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='logbook_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='placements.application')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logbook Entry',
                'verbose_name_plural': 'Logbook Entries',
                'ordering': ['-date'],
                'unique_together': {('application', 'date')},
            },
        ),
    ]
